{
    "name": "Nómina Chilena Simpledigital",
    "version": "18.0.1.0.0",
    "category": "Localization",
    "summary": "Módulo de nómina chilena desarrollado por Simpledigital.cl",
    "author": "Simpledigital.cl",
    "website": "https://simpledigital.cl",
    "license": "AGPL-3",
    "depends": ["base","hr","hr_payroll","hr_work_entry","mail", "hr_payroll_account"],
    "data": [
        'data/hr_salary_structure.xml',
        'data/hr_salary_rule.xml',
        'security/groups_payroll.xml',
        'security/ir.model.access.csv',
        'data/hr_causal_contract_end_data.xml',
        'views/hr_ccaf_deduction.xml',
        'views/hr_employee.xml',
        'views/hr_contract.xml',
        'views/hr_leave.xml',
        'views/hr_employee_movement.xml',
        'views/previred_indicator_views.xml',
        'views/hr_payroll.xml',
        'views/hr_work_entry.xml',
        'views/impuesto.xml',
        'views/res_company.xml',
        'views/res_country_commune.xml',
        'wizard/hr_previred_txt_wizard_view.xml',
        'wizard/hr_libro_remuneraciones_wizard_view.xml',
        'wizard/hr_departure_wizard_views.xml',
        'data/hr_contract_type.xml',
        'data/hr_employee_movement.xml',
        'data/hr_work_entry_type.xml',
        'data/hr_leave_type.xml',
        'data/ir_cron_data.xml',
        'data/res_country_commune_data.xml',
        'report/report_payslip_templates.xml',
        # 'data/data_testing.xml',
    ],
    "installable": True,
    "application": False,
    "price": 49.99,
    "currency": "USD",
}
