from . import hr_ccaf_deduction
from . import hr_contract
from . import hr_employee
from . import hr_employee_movement
from . import hr_employee_public
from . import hr_leave
from . import hr_payslip
from . import hr_previred_movement
from . import hr_work_entry
from . import impuesto
from . import previred_indicator
from . import res_company
from . import res_country_commune
from . import hr_causal_contract_end
